services:
  - type: web
    name: fintwin-backend
    runtime: docker
    plan: starter
    rootDir: fintwin-backend/fintwin-backend
    dockerfilePath: fintwin-backend/fintwin-backend/Dockerfile
    dockerContext: fintwin-backend/fintwin-backend